import { afterEach, describe, expect, it, vi } from 'vitest';
import { readJabsActionMapIdFromPluginsJs } from '../../../src/services/jabs/JabsPluginsReader.ts';
import { parsePluginsJsArray, pluginBasename, readPluginEntries } from '../../../src/services/plugins/PluginsJsReader.ts';

/*
 * js/plugins.js is a script RMMZ writes, not JSON, and both editors read it: the data editor for J-ABS's action map,
 * the map editor for which plugins are enabled, which decides which plugin modules switch on. Both read it through
 * this one parser. It owes them the plugins in load order with their enabled state and parameters (always text, as
 * RMMZ writes them), entries without a name skipped, and plugins told apart by exact file name, so J-ABS is never
 * confused with J-ABS-Metrics.
 */
describe('PluginsJsReader', () =>
{
  const TEXT = [
    '// Generated by RPG Maker.',
    'var $plugins =',
    '[',
    '{"name":"j/base/J-Base","status":true,"description":"The base.","parameters":{"actorBaseTp":"0"}},',
    '{"name":"j/abs/J-ABS","status":false,"description":"Battles.","parameters":{"actionMapId":"7","nested":{"x":1}}},',
    '{"status":true},',
    '"stray",',
    '{"name":"j/abs/ext/J-ABS-Metrics","status":true,"parameters":null}',
    '];',
  ].join('\n');

  afterEach(() =>
  {
    vi.unstubAllGlobals();
  });

  it('reads every named plugin in load order, parameters as text', () =>
  {
    // Arrange: the file above.

    // Act.
    const entries = readPluginEntries(TEXT);

    // Assert.
    expect(entries)
      .toStrictEqual([
        { name: 'j/base/J-Base', status: true, description: 'The base.', parameters: { actorBaseTp: '0' } },
        { name: 'j/abs/J-ABS', status: false, description: 'Battles.', parameters: { actionMapId: '7', nested: '[object Object]' } },
        { name: 'j/abs/ext/J-ABS-Metrics', status: true, description: '', parameters: {} },
      ]);
  });

  it('refuses text with no array in it', () =>
  {
    // Arrange: a file cut short.

    // Act.
    const parse = () => parsePluginsJsArray('var $plugins = ');

    // Assert.
    expect(parse)
      .toThrow('plugins.js: could not locate JSON array');
  });

  it('tells plugins apart by their exact file name', () =>
  {
    // Arrange: a path, a near namesake, and a bare name.

    // Act.
    const names = [ pluginBasename('j/abs/J-ABS'), pluginBasename('j/abs/ext/J-ABS-Metrics'), pluginBasename('HIME_LargeChoices') ];

    // Assert.
    expect(names)
      .toStrictEqual([ 'J-ABS', 'J-ABS-Metrics', 'HIME_LargeChoices' ]);
  });

  it('still gives the data editor J-ABS\'s action map through the shared parser', async () =>
  {
    // Arrange.
    vi.stubGlobal('fetch', vi.fn(async () => new Response(TEXT)));

    // Act.
    const actionMapId = await readJabsActionMapIdFromPluginsJs('');

    // Assert.
    expect(actionMapId)
      .toBe(7);
  });
});
